spring:
  application:
    name: team2-backend
  profiles:
    default: local
    group:
      local: secret
      dev: secret-dev
      prod: secret-prod
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
