spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

loki:
  url: http://loki:3100

app:
  env: dev
  time-zone: ${APP_TIME_ZONE:Asia/Seoul}
  web-base-url: ${APP_WEB_BASE_URL:https://hapalin.com}
  api-base-url: ${APP_API_BASE_URL:https://dev-api.hapalin.com}
