spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
springdoc:
  swagger-ui:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: never
  metrics:
    tags:
      application: ${spring.application.name}

loki:
  url: http://loki:3100

app:
  env: prod
  time-zone: ${APP_TIME_ZONE:Asia/Seoul}
  web-base-url: ${APP_WEB_BASE_URL:https://hapalin.com}
  api-base-url: ${APP_API_BASE_URL:https://api.hapalin.com}

candle-blow:
  duration-seconds: 180
