events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11 valid=30s;

    # dev - 8081 포트로 접근
    server {
        listen 8081;
        server_name _;

        location / {
            set $dev_upstream http://app-dev:8080;
            proxy_pass $dev_upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_connect_timeout 60s;
            proxy_read_timeout 120s;
            proxy_send_timeout 60s;
        }
    }

    # prod - 80 포트로 접근
    server {
        listen 80;
        server_name _;

        location / {
            set $prod_upstream http://app-prod:8080;
            proxy_pass $prod_upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_connect_timeout 60s;
            proxy_read_timeout 120s;
            proxy_send_timeout 60s;
        }
    }
}
