global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'team2-backend-dev'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['18th-team2-server-app-dev-1:8080']

  - job_name: 'team2-backend-prod'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['18th-team2-server-app-prod-1:8080']
