global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'team2-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      # TODO: [운영] 앱도 Docker로 띄울 경우 host.docker.internal:8080 → 앱 서비스명:8080 으로 변경
      - targets: ['host.docker.internal:8080']
