#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
STATE_DIR="$PROJECT_ROOT/.deploy-state"
ACTIVE_UPSTREAMS_FILE="$PROJECT_ROOT/nginx/conf.d/team2-active-upstreams.conf"

cd "$PROJECT_ROOT"
mkdir -p "$STATE_DIR" "$(dirname "$ACTIVE_UPSTREAMS_FILE")"

slot_or_default() {
    local env="$1"
    local state_file="$STATE_DIR/$env-active-slot"
    local slot="blue"

    if [ -f "$state_file" ]; then
        slot="$(cat "$state_file")"
    fi

    if [[ "$slot" =~ ^(blue|green)$ ]]; then
        echo "$slot"
    else
        echo "blue"
    fi
}

render_active_upstreams() {
    local dev_slot
    local prod_slot

    dev_slot="$(slot_or_default dev)"
    prod_slot="$(slot_or_default prod)"

    cat > "$ACTIVE_UPSTREAMS_FILE" <<EOF
# Generated by scripts/deploy-nginx.sh. Do not edit on the server.
map \$host \$api_upstream {
    api.hapalin.com http://app-prod-$prod_slot:8080;
    dev-api.hapalin.com http://app-dev-$dev_slot:8080;
    default "";
}

map \$host \$legacy_dev_upstream {
    default http://app-dev-$dev_slot:8080;
}
EOF
}

for network in dev-network prod-network; do
    if ! docker network inspect "$network" &>/dev/null; then
        echo "==> Creating network: $network"
        docker network create "$network"
    fi
done

EXISTING_CONTAINER_ID="$(docker ps -aq -f name='^/team2-nginx$' | head -n 1)"
if [ -n "$EXISTING_CONTAINER_ID" ]; then
    EXISTING_PROJECT="$(docker inspect -f '{{ index .Config.Labels "com.docker.compose.project" }}' "$EXISTING_CONTAINER_ID" 2>/dev/null || true)"
    if [ "$EXISTING_PROJECT" != "team2-nginx" ]; then
        echo "==> Removing legacy nginx container: team2-nginx"
        docker stop "$EXISTING_CONTAINER_ID" >/dev/null 2>&1 || true
        docker rm "$EXISTING_CONTAINER_ID" >/dev/null
    fi
fi

NGINX_FILES="-f docker/docker-compose.nginx.yml"

echo "==> Rendering active nginx upstreams..."
render_active_upstreams

echo "==> Stopping nginx..."
docker compose $NGINX_FILES down --remove-orphans

echo "==> Starting nginx..."
docker compose $NGINX_FILES up -d

if ! docker compose $NGINX_FILES exec -T nginx nginx -t; then
    echo "ERROR: nginx config test failed. Dumping logs:"
    docker compose $NGINX_FILES logs --tail=50 nginx
    exit 1
fi

if ! docker compose $NGINX_FILES ps --status running --services | grep -qx nginx; then
    echo "ERROR: nginx is not running. Dumping logs:"
    docker compose $NGINX_FILES logs --tail=50 nginx
    exit 1
fi

echo "==> Done!"
