#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
STATE_DIR="$PROJECT_ROOT/.deploy-state"
ACTIVE_UPSTREAMS_FILE="$PROJECT_ROOT/nginx/conf.d/team2-active-upstreams.conf"
ACTIVE_UPSTREAMS_BACKUP="$PROJECT_ROOT/nginx/conf.d/team2-active-upstreams.conf.bak"

cd "$PROJECT_ROOT"
mkdir -p "$STATE_DIR" "$(dirname "$ACTIVE_UPSTREAMS_FILE")"

is_valid_slot() {
    [[ "${1:-}" =~ ^(blue|green)$ ]]
}

app_container() {
    local app_env="$1"
    local slot="$2"
    echo "team2-app-$app_env-$slot"
}

legacy_app_container() {
    echo "team2-app-$1"
}

container_running() {
    local container="$1"
    [ "$(docker inspect -f '{{.State.Running}}' "$container" 2>/dev/null || true)" = "true" ]
}

container_health() {
    local container="$1"
    docker inspect -f '{{if .State.Health}}{{.State.Health.Status}}{{else}}none{{end}}' "$container" 2>/dev/null || true
}

container_ready() {
    local container="$1"
    local health

    if ! container_running "$container"; then
        return 1
    fi

    health="$(container_health "$container")"
    [ "$health" = "healthy" ] || [ "$health" = "none" ]
}

detect_active_target() {
    local app_env="$1"
    local state_file="$STATE_DIR/$app_env-active-slot"
    local state
    local slot

    if [ -f "$state_file" ]; then
        state="$(cat "$state_file")"
        if is_valid_slot "$state" && container_ready "$(app_container "$app_env" "$state")"; then
            echo "$state"
            return 0
        fi
    fi

    for slot in blue green; do
        if container_ready "$(app_container "$app_env" "$slot")"; then
            echo "$slot"
            return 0
        fi
    done

    if container_ready "$(legacy_app_container "$app_env")"; then
        echo "legacy"
        return 0
    fi

    echo "none"
}

upstream_map_value() {
    local app_env="$1"
    local target="$2"

    if [ "$target" = "legacy" ]; then
        echo "http://app-$app_env:8080"
    elif is_valid_slot "$target"; then
        echo "http://app-$app_env-$target:8080"
    else
        echo '""'
    fi
}

upstream_available() {
    local target="$1"

    if [ "$target" = "legacy" ] || is_valid_slot "$target"; then
        echo "1"
    else
        echo "0"
    fi
}

render_active_upstreams() {
    local dev_target
    local prod_target
    local dev_upstream
    local prod_upstream
    local dev_available
    local prod_available

    dev_target="$(detect_active_target dev)"
    prod_target="$(detect_active_target prod)"
    dev_upstream="$(upstream_map_value dev "$dev_target")"
    prod_upstream="$(upstream_map_value prod "$prod_target")"
    dev_available="$(upstream_available "$dev_target")"
    prod_available="$(upstream_available "$prod_target")"

    cat > "$ACTIVE_UPSTREAMS_FILE" <<EOF
# Generated by scripts/deploy-nginx.sh. Do not edit on the server.
map \$host \$api_upstream {
    api.hapalin.com $prod_upstream;
    dev-api.hapalin.com $dev_upstream;
    default "";
}

map \$host \$api_upstream_available {
    api.hapalin.com $prod_available;
    dev-api.hapalin.com $dev_available;
    default 0;
}

map \$host \$legacy_dev_upstream {
    default $dev_upstream;
}

map \$host \$legacy_dev_upstream_available {
    default $dev_available;
}
EOF
}

render_unavailable_upstreams() {
    cat > "$ACTIVE_UPSTREAMS_FILE" <<EOF
# Generated by scripts/deploy-nginx.sh. Do not edit on the server.
map \$host \$api_upstream {
    default "";
}

map \$host \$api_upstream_available {
    default 0;
}

map \$host \$legacy_dev_upstream {
    default "";
}

map \$host \$legacy_dev_upstream_available {
    default 0;
}
EOF
}

backup_active_upstreams() {
    if [ -f "$ACTIVE_UPSTREAMS_FILE" ]; then
        cp "$ACTIVE_UPSTREAMS_FILE" "$ACTIVE_UPSTREAMS_BACKUP"
    else
        rm -f "$ACTIVE_UPSTREAMS_BACKUP"
    fi
}

restore_active_upstreams() {
    if [ -f "$ACTIVE_UPSTREAMS_BACKUP" ]; then
        mv "$ACTIVE_UPSTREAMS_BACKUP" "$ACTIVE_UPSTREAMS_FILE"
    else
        render_unavailable_upstreams
    fi
}

install_active_upstreams_for_running_container() {
    if docker ps --filter 'name=^/team2-nginx$' --format '{{.Names}}' | grep -qx 'team2-nginx'; then
        local cp_error
        cp_error="$(mktemp)"

        if docker cp "$ACTIVE_UPSTREAMS_FILE" team2-nginx:/etc/nginx/conf.d/team2-active-upstreams.conf 2>"$cp_error"; then
            rm -f "$cp_error"
            return 0
        fi

        if docker exec team2-nginx cat /etc/nginx/conf.d/team2-active-upstreams.conf 2>/dev/null | cmp -s "$ACTIVE_UPSTREAMS_FILE" -; then
            rm -f "$cp_error"
            echo "==> team2-nginx already sees $ACTIVE_UPSTREAMS_FILE through a bind mount."
            return 0
        fi

        echo "ERROR: failed to install $ACTIVE_UPSTREAMS_FILE into team2-nginx"
        cat "$cp_error"
        rm -f "$cp_error"
        return 1
    fi
}

for network in dev-network prod-network; do
    if ! docker network inspect "$network" &>/dev/null; then
        echo "==> Creating network: $network"
        docker network create "$network"
    fi
done

EXISTING_CONTAINER_ID="$(docker ps -aq -f name='^/team2-nginx$' | head -n 1)"
if [ -n "$EXISTING_CONTAINER_ID" ]; then
    EXISTING_PROJECT="$(docker inspect -f '{{ index .Config.Labels "com.docker.compose.project" }}' "$EXISTING_CONTAINER_ID" 2>/dev/null || true)"
    if [ "$EXISTING_PROJECT" != "team2-nginx" ]; then
        echo "==> Removing legacy nginx container: team2-nginx"
        docker stop "$EXISTING_CONTAINER_ID" >/dev/null 2>&1 || true
        docker rm "$EXISTING_CONTAINER_ID" >/dev/null
    fi
fi

NGINX_FILES="-f docker/docker-compose.nginx.yml"

echo "==> Rendering active nginx upstreams..."
backup_active_upstreams
render_active_upstreams

if docker ps --filter 'name=^/team2-nginx$' --format '{{.Names}}' | grep -qx 'team2-nginx'; then
    if ! install_active_upstreams_for_running_container || ! docker exec team2-nginx nginx -t; then
        echo "ERROR: nginx config test failed before compose update. Restoring previous upstream file."
        restore_active_upstreams
        install_active_upstreams_for_running_container || true
        docker exec team2-nginx nginx -s reload || true
        exit 1
    fi
fi

echo "==> Applying nginx compose configuration..."
if ! docker compose $NGINX_FILES up -d --remove-orphans; then
    echo "ERROR: failed to apply nginx compose configuration. Restoring previous upstream file."
    restore_active_upstreams
    docker compose $NGINX_FILES up -d || true
    docker compose $NGINX_FILES logs --tail=50 nginx
    exit 1
fi

if ! docker compose $NGINX_FILES ps --status running --services | grep -qx nginx; then
    echo "ERROR: nginx is not running. Restoring previous upstream file."
    restore_active_upstreams
    docker compose $NGINX_FILES up -d || true
    docker compose $NGINX_FILES logs --tail=50 nginx
    exit 1
fi

if ! docker compose $NGINX_FILES exec -T nginx nginx -t; then
    echo "ERROR: nginx config test failed. Restoring previous upstream file."
    restore_active_upstreams
    docker compose $NGINX_FILES up -d || true
    docker compose $NGINX_FILES logs --tail=50 nginx
    exit 1
fi

docker compose $NGINX_FILES exec -T nginx nginx -s reload
rm -f "$ACTIVE_UPSTREAMS_BACKUP"

echo "==> Done!"
