#!/usr/bin/env bash

if [ -z "${PROJECT_ROOT:-}" ]; then
    echo "ERROR: PROJECT_ROOT must be set before sourcing scripts/lib-deploy.sh" >&2
    exit 1
fi

STATE_DIR="$PROJECT_ROOT/.deploy-state"
NGINX_CONF_DIR="$PROJECT_ROOT/nginx/conf.d"

is_valid_slot() {
    [[ "${1:-}" =~ ^(blue|green)$ ]]
}

other_slot() {
    if [ "$1" = "blue" ]; then
        echo "green"
    else
        echo "blue"
    fi
}

app_container() {
    local app_env="$1"
    local slot="$2"
    echo "team2-app-$app_env-$slot"
}

legacy_app_container() {
    echo "team2-app-$1"
}

state_file() {
    echo "$STATE_DIR/$1-active-slot"
}

active_upstreams_file() {
    echo "$NGINX_CONF_DIR/team2-active-upstreams-$1.conf"
}

container_running() {
    local container="$1"
    [ "$(docker inspect -f '{{.State.Running}}' "$container" 2>/dev/null || true)" = "true" ]
}

container_health() {
    local container="$1"
    docker inspect -f '{{if .State.Health}}{{.State.Health.Status}}{{else}}none{{end}}' "$container" 2>/dev/null || true
}

container_healthy() {
    local container="$1"

    container_running "$container" && [ "$(container_health "$container")" = "healthy" ]
}

legacy_container_ready() {
    local container="$1"
    local health

    if ! container_running "$container"; then
        return 1
    fi

    health="$(container_health "$container")"
    [ "$health" = "healthy" ] || [ "$health" = "none" ]
}

detect_active_target() {
    local app_env="$1"
    local state
    local slot

    if [ -f "$(state_file "$app_env")" ]; then
        state="$(cat "$(state_file "$app_env")")"
        if is_valid_slot "$state" && container_healthy "$(app_container "$app_env" "$state")"; then
            echo "$state"
            return 0
        fi
    fi

    for slot in blue green; do
        if container_healthy "$(app_container "$app_env" "$slot")"; then
            echo "$slot"
            return 0
        fi
    done

    if legacy_container_ready "$(legacy_app_container "$app_env")"; then
        echo "legacy"
        return 0
    fi

    echo "none"
}

upstream_map_value() {
    local app_env="$1"
    local target="$2"

    if [ "$target" = "legacy" ]; then
        echo "http://app-$app_env:8080"
    elif is_valid_slot "$target"; then
        echo "http://app-$app_env-$target:8080"
    else
        echo '""'
    fi
}

upstream_available() {
    local target="$1"

    if [ "$target" = "legacy" ] || is_valid_slot "$target"; then
        echo "1"
    else
        echo "0"
    fi
}

render_env_upstream() {
    local app_env="$1"
    local target="$2"
    local upstream
    local available

    upstream="$(upstream_map_value "$app_env" "$target")"
    available="$(upstream_available "$target")"

    if [ "$app_env" = "dev" ]; then
        cat > "$(active_upstreams_file dev)" <<EOF
# Generated by deployment scripts. Do not edit on the server.
map \$host \$dev_api_upstream {
    dev-api.hapalin.com $upstream;
    default "";
}

map \$host \$dev_api_upstream_available {
    dev-api.hapalin.com $available;
    default 0;
}

map \$host \$dev_http_upstream {
    default $upstream;
}

map \$host \$dev_http_upstream_available {
    default $available;
}
EOF
    elif [ "$app_env" = "prod" ]; then
        cat > "$(active_upstreams_file prod)" <<EOF
# Generated by deployment scripts. Do not edit on the server.
map \$host \$prod_api_upstream {
    api.hapalin.com $upstream;
    default "";
}

map \$host \$prod_api_upstream_available {
    api.hapalin.com $available;
    default 0;
}
EOF
    else
        echo "ERROR: unknown app environment: $app_env"
        return 1
    fi
}

render_detected_env_upstream() {
    local app_env="$1"
    render_env_upstream "$app_env" "$(detect_active_target "$app_env")"
}

render_all_detected_upstreams() {
    render_detected_env_upstream dev
    render_detected_env_upstream prod
}

ensure_fallback_upstreams() {
    mkdir -p "$STATE_DIR" "$NGINX_CONF_DIR"

    if [ ! -f "$(active_upstreams_file dev)" ]; then
        render_env_upstream dev none
    fi

    if [ ! -f "$(active_upstreams_file prod)" ]; then
        render_env_upstream prod none
    fi
}

install_nginx_upstream_file_for_running_container() {
    local file="$1"
    local destination="/etc/nginx/conf.d/$(basename "$file")"

    if docker ps --filter 'name=^/team2-nginx$' --format '{{.Names}}' | grep -qx 'team2-nginx'; then
        local cp_error
        cp_error="$(mktemp)"

        if docker cp "$file" "team2-nginx:$destination" 2>"$cp_error"; then
            rm -f "$cp_error"
            return 0
        fi

        if docker exec team2-nginx cat "$destination" 2>/dev/null | cmp -s "$file" -; then
            rm -f "$cp_error"
            echo "==> team2-nginx already sees $file through a bind mount."
            return 0
        fi

        echo "ERROR: failed to install $file into team2-nginx:$destination"
        cat "$cp_error"
        rm -f "$cp_error"
        return 1
    fi
}

install_nginx_upstreams_for_running_container() {
    install_nginx_upstream_file_for_running_container "$(active_upstreams_file dev)" || return 1
    install_nginx_upstream_file_for_running_container "$(active_upstreams_file prod)" || return 1
}
