name: Deploy Dev

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy to server
        run: |
          cd ${{ secrets.PROJECT_PATH }}
          git checkout develop
          git pull origin develop
          ./scripts/deploy.sh dev
