name: Deploy Dev

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy to server
        run: |
          cd ${{ secrets.PROJECT_PATH }}
          git fetch origin develop
          git reset --hard origin/develop
          git submodule update --init --recursive
          ./scripts/deploy.sh dev
